# Generated by Django 4.2.6 on 2023-12-24 17:39

import app_auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=app_auth.models.user_directory_path, verbose_name='avatar image')),
                ('alt', models.CharField(default='image', max_length=70, verbose_name='alternative text')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_auth.profile')),
            ],
        ),
    ]
