# Generated by Django 4.2.6 on 2023-12-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Phone number'),
        ),
    ]
