# Generated by Django 4.2.6 on 2024-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Delivery city'),
        ),
    ]
