# Generated by Django 4.2.6 on 2024-07-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_profile_default_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Delivery address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_delivery_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Type of delivery'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_payment_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Type of payment'),
        ),
    ]
