version: "3.9"

services:
  django_store:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - --chdir
      - /django_store/store
      - store.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    expose:
      - "8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./store/database:/store/database
      - ./store/media:/store/media
      - ./store/static:/store/static

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./store/static:/store/static
      - ./store/media:/store/media
    depends_on:
      - django_store
    restart: always