version: "3.9"

services:
  django_store:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - --chdir
      - /django_store/store
      - store.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    expose:
      - "8000"
    restart: always
    env_file:
      - .env
    environment:
      - IN_DOCKER=1
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./store/database:/store/database
      - ./store/media:/store/media
      - ./store/static:/store/static

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.template:/etc/nginx/nginx.template:ro
      - ./store/static:/store/static
      - ./store/media:/store/media
    command: /bin/sh -c "envsubst '$$ADMIN_IP' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - django_store
    restart: always