# Generated by Django 4.2.6 on 2023-12-25 19:56

import app_products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Specification name')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text review')),
                ('rate', models.PositiveSmallIntegerField(verbose_name='Rate')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of posting on the site')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='rating')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='Is Free delivery')),
                ('specifications', models.ManyToManyField(to='app_products.specification')),
                ('tags', models.ManyToManyField(to='app_products.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=app_products.models.image_dir_path, verbose_name='Product image')),
                ('alt', models.CharField(default='image', max_length=70, verbose_name='alternative text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.product')),
            ],
        ),
    ]
