# Generated by Django 4.2.6 on 2024-02-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app_products.tag'),
        ),
    ]
