# Generated by Django 4.2.6 on 2024-02-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='app_products.specification'),
        ),
    ]
