# Generated by Django 4.2.6 on 2024-02-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_alter_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0, verbose_name='already sold'),
        ),
    ]
