# Generated by Django 4.2.6 on 2024-03-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discounted price'),
        ),
    ]
