# Generated by Django 4.2.6 on 2024-06-16 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0009_alter_saleitem_sale_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Order created time')),
                ('delivery_type', models.CharField(max_length=255, verbose_name='Type of delivery')),
                ('payment_type', models.CharField(max_length=255, verbose_name='Type of payment')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total cost')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('city', models.CharField(max_length=50, verbose_name='Delivery city')),
                ('address', models.CharField(max_length=255, verbose_name='Delivery address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='app_order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.product')),
            ],
        ),
    ]
