# Generated by Django 4.2.6 on 2024-06-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_email',
            field=models.EmailField(default='testmail@testmail.com', max_length=254, verbose_name='Email for delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(default='testname', max_length=149, verbose_name='Full name for delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Phone number for delivery'),
        ),
    ]
