# Generated by Django 4.2.6 on 2024-02-08 08:48

import app_catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('parent_category', models.ForeignKey(blank=True, on_delete=models.SET(''), to='app_catalog.catalogitem')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=app_catalog.models.image_dir_path, verbose_name='Catalog item image')),
                ('alt', models.CharField(default='image', max_length=70, verbose_name='alternative text')),
                ('catalog_item', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app_catalog.catalogitem')),
            ],
        ),
    ]
