# Generated by Django 4.2.6 on 2024-02-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='app_catalog.catalogitem'),
        ),
        migrations.AlterField(
            model_name='image',
            name='catalog_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app_catalog.catalogitem'),
        ),
    ]
