# Generated by Django 4.2.6 on 2024-02-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_alter_catalogitem_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='catalog_item', to='app_catalog.catalogitem'),
        ),
    ]
