# Generated by Django 4.2.6 on 2024-02-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0003_alter_catalogitem_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='catalog_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='app_catalog.catalogitem'),
        ),
    ]
